JUDGE0_TELEMETRY_ENABLE=false
ENABLE_WAIT_RESULT=true
ENABLE_BATCHED_SUBMISSIONS=true
MAX_SUBMISSION_BATCH_SIZE=20
COUNT=1
MAX_QUEUE_SIZE=20

REDIS_HOST=judge0-redis
REDIS_PORT=6379
REDIS_PASSWORD=judge0

POSTGRES_HOST=judge0-postgres
POSTGRES_PORT=5432
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=judge0

CPU_TIME_LIMIT=2
MAX_CPU_TIME_LIMIT=2
WALL_TIME_LIMIT=5
MAX_WALL_TIME_LIMIT=5
MEMORY_LIMIT=128000
MAX_MEMORY_LIMIT=128000

RAILS_ENV=production
RAILS_MAX_THREADS=2
RAILS_SERVER_PROCESSES=1
SECRET_KEY_BASE=edutask-local-judge0-secret-key-base-change-me
